region        = "eu-west-1"
tag1          = "this is created from terraform for test"
bucket_name   = "bucket-demo-terraform-hypha-test"
ami           = "ami-0c1c30571d2dae5c9"
instance_type = "t3.micro"