name: terrafrom ci/cd apply
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - pre_prod
          - prod


jobs:
  plan:
    name: terrform plan
    runs-on: ubuntu-latest

    steps:
    - uses: hashicorp/setup-terraform@v4  
    - uses: actions/checkout@v6
    - name: Configure AWS Credentials
    -  uses: aws-actions/configure-aws-credentials@v6.1.0
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
    - run: terraform init
    - name: Terraform Plan (dev)
      if: github.event.inputs.environment == 'dev'
      run: |
          terraform plan \
            -var-file=dev.tfvars \
            -out=tfplan \
            -lock=true
    - name: Terraform Plan (test)
      if: github.event.inputs.environment == 'test'
      run: |
          terraform plan \
            -var-file=test.tfvars \
            -out=tfplan \
            -lock=true
    - name: Terraform Plan ( pre_prod)
      if: github.event.inputs.environment == 'pre_prod'
      run: |
          terraform plan \
            -var-file=pre_prod.tfvars \
            -out=tfplan \
            -lock=true
    - name: Terraform Plan (prod)
      if: github.event.inputs.environment == 'prod'
      run: |
          terraform plan \
            -var-file=prod.tfvars \
            -out=tfplan \
            -lock=true            
  apply:  
    name: terrform apply
    runs-on: ubuntu-latest

    steps:
    - uses: hashicorp/setup-terraform@v6  
    - uses: actions/checkout@v4
    - name: Configure AWS Credentials
    -  uses: aws-actions/configure-aws-credentials@v6.1.0
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
    - run: terraform init
    - name: Terraform apply (dev)
      if: github.event.inputs.environment == 'dev'
      run: |
          terraform apply \
            -var-file=dev.tfvars \
            -out=tfplan \
            -lock=true
    - name: Terraform apply  (test)
      if: github.event.inputs.environment == 'test'
      run: |
          terraform apply \
            -var-file=test.tfvars \
            -out=tfplan \
            -lock=true
    - name: Terraform apply  ( pre_prod)
      if: github.event.inputs.environment == 'pre_prod'
      run: |
          terraform apply \
            -var-file=pre_prod.tfvars \
            -out=tfplan \
            -lock=true
    - name: Terraform apply (prod)
      if: github.event.inputs.environment == 'prod'
      run: |
          terraform apply \
            -var-file=prod.tfvars \
            -out=tfplan \
            -lock=true 